sudo: required

language: node_js

services:
  - docker

before_install:
  - cd e2e
  - docker build -t parity parity
  - docker build -t e2e .
  - cd ..

script:
  - npm run lint
  - npm test
  - cd e2e && ./run-tests.sh

env:
  - HOME_RPC_URL=http://example.com FOREIGN_RPC_URL=http://example.com
