version: '2'

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - alertmanager

  grafana:
    image: grafana/grafana
    restart: always
    user: "104"
    environment:
      VIRTUAL_HOST: $MONITORING_HOSTNAME
      LETSENCRYPT_HOST: $MONITORING_HOSTNAME
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    restart: always
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  monitor:
    image: thundercore/bridge-monitor
    build: ../../monitor
    restart: always
    env_file: ./.env
    volumes:
      - ./config.json:/app/config.json

networks:
  default:
    external:
      name: frontend_default