version: '2'

services:
  contracts:
    image: thundercore/bridge-contracts
    build: ../../contracts
    env_file: ./.env
    volumes:
      - ./result.json:/app/deploy/bridgeDeploymentResults.json
